##########################################################################################################################
# File automatically-generated by STM32forVSCode
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#   2024-04-27 - Added env file inclusion. 
#                Added way to overide: build directory, target name and optimisation.
#                Added GCC_PATH by env file to not make the makefile machine dependent.
#                Currently folder structure in build directory is preserved
#                Switching of debug/release build output folder now happens based on debug flag
#   2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# Environment Variables
######################################
# Imports the environment file in which the compiler and other tooling is set
# for the build machine.
# This can also be used to overwrite some makefile variables
file_exists = $(or $(and $(wildcard $(1)),1),0)
ifeq ($(call file_exists,.stm32env),1)
  include .stm32env
endif

######################################
# Target
######################################
# This is the name of the embedded target which will be build
# The final file name will also have debug or release appended to it.
TARGET ?= pedai-sw

#######################################
# Build directories
#######################################
# Build path can be overwritten when calling make or setting the environment variable
# in .stm32env

BUILD_DIRECTORY ?= build


######################################
# Optimization
######################################
# Optimization is switched based upon the DEBUG variable. If set to 1
# it will be build in debug mode with the Og optimization flag (optimized for debugging).
# If set to 0 (false) then by default the variable is used in the configuration yaml
# This can also be overwritten using the environment variable or by overwriting it
# by calling make with the OPTIMIZATION variable e.g.:
# make -f STM32Make.make -j 16  OPTIMIZATION=Os

# variable which determines if it is a debug build
DEBUG ?= 1

# debug flags when debug is defined
OPTIMIZATION ?= -O0

RELEASE_DIRECTORY = $(BUILD_DIRECTORY)/debug
ifeq ($(DEBUG),1)
  # Sets debugging optimization -Og and the debug information output
  OPTIMIZATION_FLAGS += -Og -g -gdwarf -ggdb
  $(TARGET) := $(TARGET)-debug
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/debug
else
  OPTIMIZATION_FLAGS += $(OPTIMIZATION)
  $(TARGET) := $(TARGET)-release
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/release
endif

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Lib/tinyusb/src/class/audio/audio_device.c \
Core/Lib/tinyusb/src/class/bth/bth_device.c \
Core/Lib/tinyusb/src/class/cdc/cdc_device.c \
Core/Lib/tinyusb/src/class/cdc/cdc_host.c \
Core/Lib/tinyusb/src/class/cdc/cdc_rndis_host.c \
Core/Lib/tinyusb/src/class/dfu/dfu_device.c \
Core/Lib/tinyusb/src/class/dfu/dfu_rt_device.c \
Core/Lib/tinyusb/src/class/hid/hid_device.c \
Core/Lib/tinyusb/src/class/hid/hid_host.c \
Core/Lib/tinyusb/src/class/midi/midi_device.c \
Core/Lib/tinyusb/src/class/msc/msc_device.c \
Core/Lib/tinyusb/src/class/msc/msc_host.c \
Core/Lib/tinyusb/src/class/net/ecm_rndis_device.c \
Core/Lib/tinyusb/src/class/net/ncm_device.c \
Core/Lib/tinyusb/src/class/usbtmc/usbtmc_device.c \
Core/Lib/tinyusb/src/class/vendor/vendor_device.c \
Core/Lib/tinyusb/src/class/vendor/vendor_host.c \
Core/Lib/tinyusb/src/class/video/video_device.c \
Core/Lib/tinyusb/src/common/tusb_fifo.c \
Core/Lib/tinyusb/src/device/usbd.c \
Core/Lib/tinyusb/src/device/usbd_control.c \
Core/Lib/tinyusb/src/host/hub.c \
Core/Lib/tinyusb/src/host/usbh.c \
Core/Lib/tinyusb/src/portable/analog/max3421/hcd_max3421.c \
Core/Lib/tinyusb/src/portable/bridgetek/ft9xx/dcd_ft9xx.c \
Core/Lib/tinyusb/src/portable/chipidea/ci_fs/dcd_ci_fs.c \
Core/Lib/tinyusb/src/portable/chipidea/ci_hs/dcd_ci_hs.c \
Core/Lib/tinyusb/src/portable/chipidea/ci_hs/hcd_ci_hs.c \
Core/Lib/tinyusb/src/portable/dialog/da146xx/dcd_da146xx.c \
Core/Lib/tinyusb/src/portable/ehci/ehci.c \
Core/Lib/tinyusb/src/portable/espressif/esp32sx/dcd_esp32sx.c \
Core/Lib/tinyusb/src/portable/mentor/musb/dcd_musb.c \
Core/Lib/tinyusb/src/portable/mentor/musb/hcd_musb.c \
Core/Lib/tinyusb/src/portable/microchip/pic/dcd_pic.c \
Core/Lib/tinyusb/src/portable/microchip/pic32mz/dcd_pic32mz.c \
Core/Lib/tinyusb/src/portable/microchip/samd/dcd_samd.c \
Core/Lib/tinyusb/src/portable/microchip/samg/dcd_samg.c \
Core/Lib/tinyusb/src/portable/microchip/samx7x/dcd_samx7x.c \
Core/Lib/tinyusb/src/portable/mindmotion/mm32/dcd_mm32f327x_otg.c \
Core/Lib/tinyusb/src/portable/nordic/nrf5x/dcd_nrf5x.c \
Core/Lib/tinyusb/src/portable/nuvoton/nuc120/dcd_nuc120.c \
Core/Lib/tinyusb/src/portable/nuvoton/nuc121/dcd_nuc121.c \
Core/Lib/tinyusb/src/portable/nuvoton/nuc505/dcd_nuc505.c \
Core/Lib/tinyusb/src/portable/nxp/khci/dcd_khci.c \
Core/Lib/tinyusb/src/portable/nxp/khci/hcd_khci.c \
Core/Lib/tinyusb/src/portable/nxp/lpc17_40/dcd_lpc17_40.c \
Core/Lib/tinyusb/src/portable/nxp/lpc17_40/hcd_lpc17_40.c \
Core/Lib/tinyusb/src/portable/nxp/lpc_ip3511/dcd_lpc_ip3511.c \
Core/Lib/tinyusb/src/portable/ohci/ohci.c \
Core/Lib/tinyusb/src/portable/raspberrypi/pio_usb/dcd_pio_usb.c \
Core/Lib/tinyusb/src/portable/raspberrypi/pio_usb/hcd_pio_usb.c \
Core/Lib/tinyusb/src/portable/raspberrypi/rp2040/dcd_rp2040.c \
Core/Lib/tinyusb/src/portable/raspberrypi/rp2040/hcd_rp2040.c \
Core/Lib/tinyusb/src/portable/raspberrypi/rp2040/rp2040_usb.c \
Core/Lib/tinyusb/src/portable/renesas/rusb2/dcd_rusb2.c \
Core/Lib/tinyusb/src/portable/renesas/rusb2/hcd_rusb2.c \
Core/Lib/tinyusb/src/portable/renesas/rusb2/rusb2_common.c \
Core/Lib/tinyusb/src/portable/sony/cxd56/dcd_cxd56.c \
Core/Lib/tinyusb/src/portable/st/stm32_fsdev/dcd_stm32_fsdev.c \
Core/Lib/tinyusb/src/portable/st/typec/typec_stm32.c \
Core/Lib/tinyusb/src/portable/sunxi/dcd_sunxi_musb.c \
Core/Lib/tinyusb/src/portable/synopsys/dwc2/dcd_dwc2.c \
Core/Lib/tinyusb/src/portable/synopsys/dwc2/dwc2_common.c \
Core/Lib/tinyusb/src/portable/synopsys/dwc2/hcd_dwc2.c \
Core/Lib/tinyusb/src/portable/template/dcd_template.c \
Core/Lib/tinyusb/src/portable/template/hcd_template.c \
Core/Lib/tinyusb/src/portable/ti/msp430x5xx/dcd_msp430x5xx.c \
Core/Lib/tinyusb/src/portable/valentyusb/eptri/dcd_eptri.c \
Core/Lib/tinyusb/src/portable/wch/dcd_ch32_usbfs.c \
Core/Lib/tinyusb/src/portable/wch/dcd_ch32_usbhs.c \
Core/Lib/tinyusb/src/tusb.c \
Core/Lib/tinyusb/src/typec/usbc.c \
Core/Src/key_reader.c \
Core/Src/lcd1602a.c \
Core/Src/main.c \
Core/Src/midi_player.c \
Core/Src/msc_disk.c \
Core/Src/ped_types.c \
Core/Src/samples/sample_22kHz_D2.c \
Core/Src/sound_player.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stm32f4xx_it.c \
Core/Src/syscalls.c \
Core/Src/sysmem.c \
Core/Src/system_stm32f4xx.c \
Core/Src/usb_descriptors_cdc.c \
Core/Src/usb_descriptors_midi.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q15.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q15.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/TransformFunctions.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c


CXX_SOURCES = \


# ASM sources
ASM_SOURCES =  \
startup_stm32f411xe.s


#######################################
# Tools
#######################################
ARM_PREFIX = arm-none-eabi-
POSTFIX = "
PREFIX = "
# The gcc compiler bin path can be defined in the make command via ARM_GCC_PATH variable (e.g.: make ARM_GCC_PATH=xxx)
# or it can be added to the PATH environment variable.
# By default the variable be used from the environment file: .stm32env.
# if it is not defined

ifdef ARM_GCC_PATH
    CC = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX)
    CXX = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)g++$(POSTFIX)
    AS = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX) -x assembler-with-cpp
    CP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objcopy$(POSTFIX)
    SZ = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)size$(POSTFIX)
    DP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objdump$(POSTFIX)
else
  CC ?= $(ARM_PREFIX)gcc
  CXX ?= $(ARM_PREFIX)g++$
  AS ?= $(ARM_PREFIX)gcc -x assembler-with-cpp
  CP ?= $(ARM_PREFIX)objcopy
  SZ ?= $(ARM_PREFIX)size
  DP ?= $(ARM_PREFIX)objdump
endif

HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
LSS = $(DP) -h -S


REMOVE_DIRECTORY_COMMAND = rm -fR
mkdir_function = mkdir -p $(1)
ifeq ($(OS),Windows_NT)
  convert_to_windows_path = $(strip $(subst /,\,$(patsubst %/,%,$(1))))
  REMOVE_DIRECTORY_COMMAND = cmd /c rd /s /q
  mkdir_function = cmd /e:on /c if not exist $(call convert_to_windows_path,$(1)) md $(call convert_to_windows_path,$(1))
endif


# Flash and debug tools
# Default is openocd however will be gotten from the env file when existing
OPENOCD ?= openocd


#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DSTM32F411xE \
-DUSE_HAL_DRIVER


# CXX defines
CXX_DEFS =  \
-DSTM32F411xE \
-DUSE_HAL_DRIVER


# AS includes
AS_INCLUDES = \

# C includes
C_INCLUDES =  \
-ICore/Inc \
-ICore/Inc/samples \
-ICore/Lib/tinyusb/hw \
-ICore/Lib/tinyusb/hw/bsp \
-ICore/Lib/tinyusb/src \
-IDrivers/CMSIS/DSP/Include \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(C_INCLUDES) $(C_DEFS) $(OPTIMIZATION_FLAGS) 

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPTIMIZATION_FLAGS)

CXXFLAGS = $(MCU) $(CXX_DEFS) $(C_INCLUDES) $(OPTIMIZATION_FLAGS)

# Add additional flags
CFLAGS += -Wall -fdata-sections -ffunction-sections 
ASFLAGS += -Wall -fdata-sections -ffunction-sections 
CXXFLAGS += -fno-exceptions -fno-rtti 

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"
CXXFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

# Output a list file for the compiled source file.
# This is a representative of the source code in assembly
ASSEMBLER_LIST_OUTPUT_FLAG = -Wa,-a,-ad,-alms=$(call add_release_directory,$<,lst)
CFLAGS += $(ASSEMBLER_LIST_OUTPUT_FLAG)
CXXFLAGS += $(ASSEMBLER_LIST_OUTPUT_FLAG)

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F411CEUx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = \


# Additional LD Flags from config file
ADDITIONALLDFLAGS = -Wl,--print-memory-usage -specs=nano.specs 

LDFLAGS = $(MCU) $(ADDITIONALLDFLAGS) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIRECTORY)/$(TARGET).map,--cref -Wl,--gc-sections

#######################################
# build the application
#######################################
add_release_directory = $(sort $(addprefix $(RELEASE_DIRECTORY)/,$(addsuffix .$(2),$(basename $(notdir $(1))))))



OBJECTS = $(call add_release_directory,$(C_SOURCES),o)
OBJECTS += $(call add_release_directory,$(CXX_SOURCES),o)
OBJECTS += $(call add_release_directory,$(ASM_SOURCES),o)
vpath %.c $(sort $(dir $(C_SOURCES)))
vpath %.cc $(sort $(dir $(CXX_SOURCES)))
vpath %.cp $(sort $(dir $(CXX_SOURCES)))
vpath %.cxx $(sort $(dir $(CXX_SOURCES)))
vpath %.cpp $(sort $(dir $(CXX_SOURCES)))
vpath %.c++ $(sort $(dir $(CXX_SOURCES)))
vpath %.C $(sort $(dir $(CXX_SOURCES)))
vpath %.CPP $(sort $(dir $(CXX_SOURCES)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
vpath %.S $(sort $(dir $(ASM_SOURCES)))

#######################################
# all
#######################################
# note needs to be located as the first rule to be the default build rule
# default action: build all
all: $(RELEASE_DIRECTORY)/$(TARGET).elf $(RELEASE_DIRECTORY)/$(TARGET).hex $(RELEASE_DIRECTORY)/$(TARGET).bin $(RELEASE_DIRECTORY)/$(TARGET).lss 


# C build
$(RELEASE_DIRECTORY)/%.o: %.c STM32Make.make | $(RELEASE_DIRECTORY)
	$(CC) -c $(CFLAGS) $< -o $@

# C++ build 
$(RELEASE_DIRECTORY)/%.o: %.cc STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cp STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cxx STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cpp STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.c++ STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.C STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.CPP STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

#Assembly build
$(RELEASE_DIRECTORY)/%.o: %.s STM32Make.make | $(RELEASE_DIRECTORY)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.S STM32Make.make | $(RELEASE_DIRECTORY)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.sx STM32Make.make | $(RELEASE_DIRECTORY)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/$(TARGET).elf: $(OBJECTS) STM32Make.make | $(RELEASE_DIRECTORY)
	@echo $(OBJECTS) > $@.in
	$(CC) @$@.in $(LDFLAGS) -o $@
	$(SZ) $@

$(RELEASE_DIRECTORY)/%.hex: $(RELEASE_DIRECTORY)/%.elf | $(RELEASE_DIRECTORY)
	$(HEX) $< $@

$(RELEASE_DIRECTORY)/%.bin: $(RELEASE_DIRECTORY)/%.elf | $(RELEASE_DIRECTORY)
	$(BIN) $< $@

$(RELEASE_DIRECTORY)/%.lss: $(RELEASE_DIRECTORY)/%.elf | $(RELEASE_DIRECTORY)
	$(LSS) $< > $@

$(RELEASE_DIRECTORY):
	$(call mkdir_function, $@)

$(BUILD_DIRECTORY): | $(RELEASE_DIRECTORY)
	$(call mkdir_function, $@)


#######################################
# flash
#######################################
flash: all
	"$(OPENOCD)" -f ./openocd.cfg -c "program $(RELEASE_DIRECTORY)/$(TARGET).elf verify reset exit"

#######################################
# erase
#######################################
erase: all
	"$(OPENOCD)" -f ./openocd.cfg -c "init; reset halt; stm32f4x mass_erase 0; exit"

#######################################
# clean up
#######################################
clean:
	$(REMOVE_DIRECTORY_COMMAND) $(BUILD_DIRECTORY)

#######################################
# custom makefile rules
#######################################

	
#######################################
# dependencies
#######################################
-include $(wildcard $(RELEASE_DIRECTORY)/*.d)

# *** EOF ***